<?php
$config = array (
  'debug' => 0,
  'MISP' => 
  array (
    'baseurl' => 'https://dev.ecrimelabs.net',
    'footermidleft' => 'eCrimelabs Threat Intelligence Platform ',
    'footermidright' => '',
    'org' => 'eCrimeLabs',
    'showorg' => true,
    'threatlevel_in_email_subject' => true,
    'email_subject_TLP_string' => 'TLP Amber',
    'email_subject_tag' => 'tlp',
    'email_subject_include_tag_name' => true,
    'background_jobs' => true,
    'cached_attachments' => true,
    'email' => 'tip@ecrimelabs.net',
    'contact' => 'tip@ecrimelabs.net',
    'cveurl' => 'http://cve.circl.lu/cve/',
    'disablerestalert' => false,
    'default_event_distribution' => '0',
    'default_attribute_distribution' => 'event',
    'tagging' => true,
    'full_tags_on_event_index' => true,
    'attribute_tagging' => true,
    'full_tags_on_attribute_index' => true,
    'footer_logo' => '',
    'take_ownership_xml_import' => false,
    'unpublishedprivate' => false,
    'disable_emailing' => false,
    'manage_workers' => true,
    'Attributes_Values_Filter_In_Event' => 'id, uuid, value, comment, type, category, Tag.name',
    'live' => true,
    'uuid' => '5c2df6d1-a1e4-44bd-bb5f-267cc8c1ff78',
    'language' => 'eng',
    'host_org_id' => 2,
    'proposals_block_attributes' => true,
    'allow_disabling_correlation' => false,
    'title_text' => 'eCrimeLabs TIP',
    'main_logo' => 'eCrimeLabs_logo.png',
    'attachments_dir' => '/var/www/MISP/app/files/',
    'newUserText' => 'Dear new eCrimeLabs TIP user,\\n\\nWe would hereby like to welcome you to the $org TIP community.\\n\\n Use the credentials below to log into eCrimeLabs TIP at $misp, where you will be prompted to manually change your password to something of your own choice.\\n\\nUsername: $username\\nPassword: $password\\n\\nIf you have any questions, do not hesitate to contact us at: $contact.\\n\\nBest regards,\\nYour $org TIP support team',
    'passwordResetText' => 'Dear MISP user,\\n\\nA password reset has been triggered for your account. Use the below provided temporary password to log into MISP at $misp, where you will be prompted to manually change your password to something of your own choice.\\n\\nUsername: $username\\nYour temporary password: $password\\n\\nIf you have any questions, do not hesitate to contact us at: $contact.\\n\\nBest regards,\\nYour $org MISP support team',
    'disableUserSelfManagement' => false,
    'block_event_alert' => false,
    'block_event_alert_tag' => 'no-alerts="true"',
    'block_old_event_alert' => false,
    'block_old_event_alert_age' => 0,
    'disable_cached_exports' => true,
    'incoming_tags_disabled_by_default' => false,
    'maintenance_message' => 'eCrimeLabs TIP is undergoing maintenance, but will return shortly. You can contact the administration at $email.',
    'download_attachments_on_load' => true,
    'redis_host' => '127.0.0.1',
    'redis_port' => 6379,
    'redis_database' => 13,
    'redis_password' => '',
    'ssdeep_correlation_threshold' => 40,
    'extended_alert_subject' => false,
    'default_event_threat_level' => '4',
    'enableEventBlacklisting' => true,
    'enableOrgBlacklisting' => true,
    'log_client_ip' => true,
    'log_auth' => false,
    'delegation' => true,
  ),
  'GnuPG' => 
  array (
    'onlyencrypted' => false,
    'email' => 'tip@ecrimelabs.net',
    'homedir' => '/var/www/MISP/.gnupg',
    'password' => '',
    'bodyonlyencrypted' => false,
    'sign' => false,
    'binary' => '/usr/bin/gpg',
  ),
  'SMIME' => 
  array (
    'enabled' => false,
    'email' => '',
    'cert_public_sign' => '',
    'key_sign' => '',
    'password' => '',
  ),
  'Proxy' => 
  array (
    'host' => '',
    'port' => '',
    'method' => '',
    'user' => '',
    'password' => '',
  ),
  'SecureAuth' => 
  array (
    'amount' => 5,
    'expire' => 300,
  ),
  'Security' => 
  array (
    'level' => 'medium',
    'salt' => 'e82298b1f9a7c62ba441b57306ba594946de673ff920cecc2268eb5938d4f7504b66bb466a917c343f24',
    'cipherSeed' => '',
  ),
  'Session.defaults' => 'php',
  'Session.timeout' => '600',
  'Session.cookie_timeout' => 3600,
  'Session.autoRegenerate' => false,
  'Session.checkAgent' => false,
  'site_admin_debug' => NULL,
  'Plugin' => 
  array (
    'Enrichment_services_enable' => true,
    'Enrichment_hover_enable' => true,
    'Enrichment_timeout' => 10,
    'Enrichment_hover_timeout' => 5,
    'Enrichment_services_url' => 'http://127.0.0.1',
    'Enrichment_services_port' => 6666,
    'Enrichment_geoip_country_enabled' => '1',
    'Enrichment_dns_enabled' => '1',
    'Enrichment_dns_nameserver' => '1.1.1.1',
    'Enrichment_yara_syntax_validator_enabled' => '1',
    'Enrichment_cve_enabled' => '1',
    'Enrichment_reversedns_enabled' => '1',
    'Enrichment_reversedns_nameserver' => '1.1.1.1',
    'Import_services_enable' => true,
    'Import_timeout' => 10,
    'Import_services_url' => 'http://127.0.0.1',
    'Import_services_port' => 6666,
    'Export_services_enable' => true,
    'Export_services_url' => 'http://127.0.0.1',
    'Export_services_port' => 6666,
    'Export_timeout' => 10,
    'Cortex_services_enable' => false,
    'Sightings_policy' => 0,
    'Sightings_anonymise' => false,
    'Sightings_range' => 365,
    'ZeroMQ_enable' => false,
    'CustomAuth_enable' => true,
    'CustomAuth_name' => 'KKK',
    'CustomAuth_use_header_namespace' => true,
    'CustomAuth_header' => 'kkk_auth_header',
    'CustomAuth_custom_logout' => '',
    'CustomAuth_custom_password_reset' => 'https://my/custom/pw/reset',
    'CustomAuth_disable_logout' => false,
    'CustomAuth_required' => false,
    'CustomAuth_header_namespace' => 'HTTPS_',
  ),
  'CertAuth' => NULL,
  'ApacheShibbAuth' => NULL,
  'ApacheSecureAuth' => NULL,
);