language: python

cache: pip

sudo: required

python:
    - "3.6"
    - "3.6-dev"
    - "nightly"

install:
    - sudo apt-get update -qq
    - sudo apt-get install -y -qq jq moreutils
    - pip install jsonschema
    - pip install git+https://github.com/MISP/PyTaxonomies.git

script:
    - ./validate_all.sh
    - pytaxonomies -l MANIFEST.json -a
